fix: cherry picked all v9.x.x hotfix
zeta-chain/node pull request #1123
Opened 2023-09-12 19:11 UTC by ws4charlie

# Description

Cherry picked v9.x.x hot fixes.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Include instructions and any relevant details so others can reproduce. 

- [ ] Tested CCTX in localnet
- [ ] Tested in development environment
- [ ] Go unit tests
- [ ] Go integration tests
- [ ] Tested via GitHub Actions 

# Checklist:

- [ ] I have added unit tests that prove my fix feature works

2023-09-12 20:05 UTC, lumtis approved these changes
LGTM

2023-09-12 22:28 UTC, brewmaster012 requested changes
minor change request.

2023-09-12 22:28 UTC, brewmaster012 commented on zetaclient/evm_client.go
> +	8001: 120000, // Matic
matic chainid is 80001

2023-09-14 18:09 UTC, kingpinXD approved these changes

2023-09-15 18:51 UTC, ws4charlie commented on zetaclient/evm_client.go
> +	8001: 120000, // Matic
Thanks.

2023-09-15 21:12 UTC, brewmaster012 approved these changes

2023-09-16 02:54 UTC, merged