fix: State Export Manually Executed Upgrade Path Testing Pipeline Merge.
zeta-chain/node pull request #1142
Opened 2023-09-18 19:28 UTC by gzukel

# Description

This PR merges a pipeline that does upgrade path testing by standing up a network with massaged mainnet state and upgrading to the latest binary either by simply doing a binary replacement or governance upgrade if its a major version change. 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

This was tested in Github Actions pipeline 6 times with success.

- [ ] Tested CCTX in localnet
- [ ] Tested in development environment
- [ ] Go unit tests
- [ ] Go integration tests
- [x] Tested via GitHub Actions 

# Checklist:

- [x] I have added unit tests that prove my fix feature works

2023-09-18 19:39 UTC, billyyang423 approved these changes

2023-09-18 19:50 UTC, CharlieMc0 requested changes

2023-09-18 19:50 UTC, CharlieMc0 commented on .github/workflows/build.yml
> +          #go mod tidy
Please delete the whole line since go mod tidy no longer works with go 1.20

2023-09-18 19:50 UTC, CharlieMc0 commented on .github/workflows/upgrade_path_testing.yaml
> +          cat $DAEMON_HOME/config/genesis.json | jq '.app_state["gov"]["voting_params"]["voting_period"]="60s"' > $DAEMON_HOME/config/tmp_genesis.json && mv $DAEMON_HOME/config/tmp_genesis.json $DAEM
Why not complete lines 137-144 in the python script along with the other genesis file modifications?

2023-09-18 19:50 UTC, CharlieMc0 commented on .github/workflows/upgrade_path_testing.yaml
> +      - name: "NON_CONCENSUS_BREAKING_UPGRADE"
Typo `CONSENSUS` not `CONCENSUS`

2023-09-18 19:50 UTC, CharlieMc0 commented on .github/workflows/upgrade_path_testing.yaml
> +          MAX_TRIES=100
Can you set these and env variables at the job level? Just so it's easier to see what values can be tweaked for fine tuning

2023-09-18 19:50 UTC, CharlieMc0 commented on .github/workflows/upgrade_path_testing.yaml
> +              sleep $SLEEP_DURATION
Why is there a sleep at the end when there is nothing left to wait for?

2023-09-19 17:41 UTC, kingpinXD commented on .github/actions/upgrade-testing/scripts/create_genesis.py
> +        print("pop account", account["address"])
Are these values constants for Athens 3? Woudl this still work if we want to use this script to export state from a different network

2023-09-19 17:46 UTC, kingpinXD commented on .github/actions/upgrade-testing/scripts/raise_gov_proposal.py
> +GOV_PROPOSAL = f"""zetacored tx gov submit-legacy-proposal software-upgrade "{os.environ['VERSION']}" \
@gzukel  can we try moving away from the legacy proposal, and submit using the regular proposal instead?

2023-09-19 21:36 UTC, CharlieMc0 approved these changes

2023-09-21 18:31 UTC, merged