isSupported to isActive
zeta-chain/node pull request #1545
Opened 2024-01-09 18:53 UTC by Shenr0n

Fixes #1523

2024-01-09 21:41 UTC, kingpinXD approved these changes

2024-01-10 17:42 UTC, kingpinXD commented
Please run 
- `make generate` to make sure you pass generated files check 
-  add a changelog entry to clear the changelog check

2024-01-12 23:20 UTC, kingpinXD requested changes
We would also need to have a migration script to for params . To transition from the old to the new fields . 
Lets hold on to this PR for now , and the script can be added after the transition to chain params has been merged to develop

2024-02-26 09:28 UTC, closed without merging

2024-02-26 09:28 UTC, lumtis commented
It looks inactive.
Closing for now to give a chance if someone else want to address the issue.
Please, feel free to reopen.