ci: adding pipeline to build and push ubuntu, and macos docker images for zetacored
zeta-chain/node pull request #1748
Opened 2024-02-12 20:56 UTC by gzukel

# Description

This PR adds a simple pipeline for building and pushing docker images for mac and ubuntu-linux into dockerhub. This is a CI only change.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I need to merge it to test the pipeline and if there are any additional changes that need to be made I will open a PR to make them.

- [ ] Tested CCTX in localnet
- [ ] Tested in development environment
- [ ] Go unit tests
- [ ] Go integration tests
- [ ] Tested via GitHub Actions 

# Checklist:

- [N/A] I have added unit tests that prove my fix feature works

2024-02-12 20:59 UTC, lumtis commented on changelog.md
> +* CI: adding pipeline to build and push docker images into dockerhub on release for ubuntu and macos.
Can you put it under 
```
### CI
```

2024-02-12 22:06 UTC, CharlieMc0 commented on .github/workflows/docker-build-and-push.yml
> +        timeout-minutes: 8
Is that long enough? I thought our image takes a long time to build

2024-02-12 22:07 UTC, CharlieMc0 requested changes
You should be able to use builtjet to add support for ARM images as well

2024-02-13 01:25 UTC, CharlieMc0 approved these changes

2024-02-13 12:55 UTC, lumtis approved these changes

2024-02-13 13:36 UTC, merged