chore: update upgrade handler to `v13`
zeta-chain/node pull request #1777
Opened 2024-02-19 14:22 UTC by lumtis

# Description

Closes: https://github.com/zeta-chain/node/issues/1776

2024-02-19 17:10 UTC, kingpinXD approved these changes

2024-02-19 17:46 UTC, brewmaster012 requested changes

2024-02-19 17:46 UTC, brewmaster012 commented on app/setup_handlers.go
> +const releaseVersion = "v13.0.0"
i thought we would do
v13
instead of v13.0.0

2024-02-20 16:54 UTC, brewmaster012 approved these changes

2024-02-20 17:04 UTC, merged