test: full coverage for messages in types packages
zeta-chain/node pull request #1879
Opened 2024-03-11 19:32 UTC by skosito

# Description

- cover all messages in module types with unit tests

Closes: #1844 

## Type of change

unit tests

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Include instructions and any relevant details so others can reproduce. 

- [ ] Tested CCTX in localnet
- [x] Tested in development environment
- [x] Go unit tests
- [ ] Go integration tests
- [x] Tested via GitHub Actions 

# Checklist:

- [x] I have added unit tests that prove my fix feature works

2024-03-11 20:35 UTC, kingpinXD commented on x/crosschain/types/message_abort_stuck_cctx_test.go
> +			err:  nil,
Maybe lets a check in validate basic for the index and a corresponding test 
	if len(msg.CctxIndex) != 66 {
		return ErrInvalidCCTXIndex
	}
	
Alternatively, we can just create an issue for this and add this check in a separate PR . Might bee needed to add in multiple places

2024-03-11 20:36 UTC, kingpinXD commented on x/crosschain/types/message_add_to_in_tx_tracker_test.go
> +				"hash",
lets use sample.Hash()

2024-03-11 20:44 UTC, kingpinXD commented on x/crosschain/types/message_migrate_tss_funds_test.go
> +				"zeta15ruj2tc76pnj9xtw64utktee7cc7w6vzaes73z",
lets use sample.AccAddress()

2024-03-11 20:50 UTC, kingpinXD commented on x/crosschain/types/message_update_tss_address_test.go
> +				"zetapub1addwnpepq28c57cvcs0a2htsem5zxr6qnlvq9mzhmm76z3jncsnzz32rclangr2g35p",
This can be replaced by sample values too .

2024-03-11 21:21 UTC, kingpinXD commented on x/observer/types/message_crosschain_flags_test.go
> +}
Should we add a validate function for `BlockHeaderVerificationFlags` as well ?

2024-03-13 06:11 UTC, kingpinXD commented on x/observer/types/message_crosschain_flags_test.go
> +}
no I think it makes sense to cover it under `TestMsgUpdateCrosschainFlags_GetRequiredPolicyType`

2024-03-13 06:11 UTC, kingpinXD approved these changes

2024-03-13 11:33 UTC, lumtis requested changes
Looks good. We have 100% coverage for all message types on codecov👍

Just one thing: can we consider changing all `assert` to `require`? We're trying to make consistent the use of require throughout the codebase, I think it makes also simpler to debug test errors

2024-03-13 11:56 UTC, lumtis approved these changes

2024-03-13 12:36 UTC, merged