ci: expand performance testing to catch errors, fixed connection refused errors, added performance testing with state.
zeta-chain/node pull request #2400
Opened 2024-06-29 00:19 UTC by gzukel

# Description

1. Expanded the logic the pipeline to look for errors in the report json if no failures we're reported via artillery as a secondary check to ensure we know when tests fail/succeed.
2. Fixed connection refused errors. These errors we're happening locally. The issue is using the composite for artillery uses docker backed composite so the network was separate. The reports weren't clear that it was failing or if it was reporting wrong. That is corrected now.
3. Added starting a local net from the state export to performance test with state.
4. Added slack channel notification when testing fails so the DevOps team can know about it when it happens. 

# How Has This Been Tested?

I executed multiple Github Action scenarios to ensure all logic functioned as intended through failure and success scenarios.

Failed Test: https://github.com/zeta-chain/node/actions/runs/9719615016
Failed Test w/State: https://github.com/zeta-chain/node/actions/runs/9719839293
Success Test: https://github.com/zeta-chain/node/actions/runs/9719810694
Success Tests With State: https://github.com/zeta-chain/node/actions/runs/9719842212/job/26830323773

- [ ] Tested CCTX in localnet
- [ ] Tested in development environment
- [ ] Go unit tests
- [ ] Go integration tests
- [x] Tested via GitHub Actions

2024-06-30 08:28 UTC, lumtis approved these changes
LGTM

2024-06-30 19:56 UTC, CharlieMc0 reviewed
I think there is one comment leftover from your testing but other than that it looks good.

2024-06-30 19:56 UTC, CharlieMc0 commented on .github/actions/performance-tests/art.yaml
> +            method: "web3_clientVersion"  # Deliberate typo to force failure
Is `# Deliberate typo to force failure` let over from testing?

2024-07-01 15:56 UTC, gartnera requested changes

2024-07-01 15:56 UTC, gartnera commented on .github/workflows/ci-nightly-performance-testing.yaml
> +        if: failure()
Please only send the alert if it's a ` schedule` type

2024-07-01 22:26 UTC, gartnera approved these changes

2024-07-01 22:43 UTC, merged